# Camera configuration
camera_sensor_mode: 4
camera_rotation: 90
camera_framerate: 30.
camera_exposure_mode: 'sports'

# Image flip
# the bottom row of images has to flip to pu the timestamp field outside of the maze
camera_vflip: ['piEye07', 'piEye08', 'piEye09', 'piEye10', 'piEye11', 'piEye12']
camera_hflip: ['piEye07', 'piEye08', 'piEye09', 'piEye10', 'piEye11', 'piEye12']

# Frame resize. Note that frame dimensions must take rotation into account
frame_width: 600
frame_height: 800

# Preview
camera_preview_enable: false
camera_preview_alpha: 200
camera_annotate_metadata: true
camera_annotate_frame_num: true
camera_annotate_text_size: 16
camera_annotate_bg_color: 'black'

# Capture
camera_recording_format: 'mjpeg'

# Connection
zmq_output_port: 5555
zmq_topic_video: piEye

# Debug options
debug_drop_nth_frame: 0
camera_stream_duplication: 1
