# Camera configuration
camera_sensor_mode: 4
camera_rotation: 90
camera_vflip: false
camera_hflip: false
camera_framerate: 30.
camera_exposure_mode: 'sports'

# Frame resize. Note that frame dimensions must take rotation into account
frame_width: 480
frame_height: 640

# Preview
camera_preview_enable: true
camera_preview_alpha: 200
camera_annotate_metadata: true
camera_annotate_frame_num: true
camera_annotate_text_size: 16
camera_annotate_bg_color: 'black'

# Capture
camera_recording_format: 'mjpeg'

# Misc
zmq_output_port: 5555
camera_stream_duplication: 2

# Debug
debug_drop_nth_frame: 10000

