---
- hosts: new_eyes
  remote_user: pi
  become: true
  tasks:
    - name: System setup | Update all installed apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: System setup | Install basic packages
      apt:
        pkg:
          - vim
          - ntp
          - git
          - htop
          - byobu
          - python3-pip
          - python3-picamera
          - python3-zmq
          - python3-apt
          - python-setuptools  # workaround for ansible checking setuptools of the wrong python version!
          - libzbar0
        state: present

    - name: System setup | Install pip packages
      pip:
        name:
          - pyyaml
          - pyzbar
          - Pillow
        executable: pip3

    - name: System setup | Enable the raspberry camera
      lineinfile:
        path: /boot/config.txt
        regexp: '^start_x'
        line: 'start_x=1'
      register: reboot_required

    # See https://raspberrypi.stackexchange.com/q/84390/6506
    - name: System setup | Disable swap file
      shell: >
        dphys-swapfile swapoff &&
        dphys-swapfile uninstall &&
        update-rc.d -f dphys-swapfile remove
      when:
        - ansible_swaptotal_mb > 0

###########################

    - name: Time & NTP | Link Europe/Amsterdam time zone
      file:
        src: /usr/share/zoneinfo/Europe/Amsterdam
        dest: /etc/localtime
        state: link
        force: true
      register: tz_changed

    - name: Time & NTP | Update time zone
      command: dpkg-reconfigure --frontend noninteractive tzdata
      when: tz_changed

    - name: Time & NTP | Copy ntp configuration
      template:
        src: templates/timesycnd.conf.j2
        dest: /etc/systemd/timesyncd.conf
        mode: 0644

    - name: Time & NTP | Enable ntp
      command: timedatectl set-ntp true

    - name: Time & NTP | Restart timedatectl service
      systemd:
        name: systemd-timesyncd
        status: restarted

###########################

    - name: Git setup | Create 'src' directory
      become_user: pi
      file:
        path: /home/pi/src
        state: directory

    - name: Git setup | Clone BeholderPi GitHub repository
      become_user: pi
      git:
        repo: https://github.com/MemDynLab/BeholderPi
        dest: /home/pi/src/BeholderPi
        update: yes
      register: service_restart

    - name: Git setup | Add spectator as remote git repo
      become_user: pi
      command: git remote add spectator ssh://10.0.0.1/home/pi/src/BeholderPi chdir=/home/pi/src/BeholderPi
      ignore_errors: yes

###########################

    - name: Beholder services | Create symbolic link
      file:
        src: "/home/pi/src/BeholderPi/scripts/services/streaming/beholder_streaming.service"
        dest: "/etc/systemd/system/beholder_streaming.service"
        state: link

    - name: Beholder services | Enable streaming service
      systemd:
        name: beholder_streaming
        enabled: yes
      register: reboot_required

    - name: Beholder services | Reload Systemd config
      systemd:
        daemon-reload: yes
      when: service_restart

    - name: Beholder services | Populate service facts
      service_facts:
#      - debug:
#        var: ansible_facts.services

    - name: Beholder services | Restart discovery service
      systemd:
        name: beholder_discovery_sender
        state: restarted
        no_block: yes
      when: service_restart
      changed_when: False

    - name: Beholder services | Restart streaming service
      systemd:
        name: beholder_streaming
        state: restarted
        no_block: yes
      when: "'beholder_streaming.service' in services"
      changed_when: False

    - name: Telemetry | Check if telegraf is running
      systemd:
        name: telegraf
        state: started
      register: telegraf_install_required
      ignore_errors: True

    - name: Telemetry | Install InfluxDB repository key
      apt_key:
        url: https://repos.influxdata.com/influxdb.key
        state: present
      when: telegraf_install_required

    - name: Telemetry | Add InfluxDB repository deb
      apt_repository:
        repo: deb https://repos.influxdata.com/debian stretch stable
        state: present
      when: telegraf_install_required

    - name: Telemetry | Install telegraf
      apt:
        pkg: telegraf
        state: present
      when: telegraf_install_required

    - name: Telemetry | Adding telegraf user to video group
      user:
        name: telegraf
        groups: video
        append: yes

    - name: Telemetry | Check for telegraf.conf symbolic link status
      stat: path=/etc/telegraf/telegraf.conf
      register: telegraf_conf_link
#      - debug: msg="Link exists"
#      when: telegraf_conf_link.stat.islnk is defined and telegraf_conf_link.stat.islnk

    - name: Telemetry | Link repo telegraf configuration file
      command: mv /etc/telegraf/telegraf.conf /etc/telegraf/telegraf.bak
      when: telegraf_conf_link.stat.islnk is defined and not telegraf_conf_link.stat.islnk

    - name: Telemetry | Create symbolic telegraf.conf link from git repo
      file:
        src: "/home/pi/src/BeholderPi/piEye/resources/telegraf.conf"
        dest: "/etc/telegraf/telegraf.conf"
        state: link

    - name: Telemetry | Set up influxdb credentials
      template:
        src: "templates/{{ item.template }}"
        dest: "{{ item.dest }}"
        mode: 0644
      with_items:
        - { template: default.telegraf.j2, dest: /etc/default/telegraf }

    - name: Telemetry | Restart telegraf
      systemd:
        name: telegraf
        state: restarted

    - name: Reboot immediately if there was a change
      shell: "sleep 3 && reboot"
      async: 1
      poll: 0
      when: reboot_required is changed


    - name: Wait for the reboot to complete if there was a change
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when: reboot_required is changed


#  #  roles:
#  #  - update
#  #  - eye
#  #  - telegrafer
