---
#- hosts: spectator
#  remote_user: pi
#  become: true
#
#  tasks:
#  - name: Git setup | Update from 'spectator' remote to check
#    become_user: pi
#    git:
#      repo: ssh://beholder/home/pi/src/BeholderPi
#      update: yes
#      dest: /home/pi/src/BeholderPi
#      remote: beholder
#    register: service_restart
- hosts: spectator
  remote_user: pi
  become: true

  tasks:
    - name: Update all installed apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
      ignore_errors: true
      no_log: true

    - name: Git setup | Update from 'beholder' remote
      become_user: pi
      git:
        repo: ssh://beholder/home/mdadmin/src/BeholderPi
        update: yes
        dest: /home/pi/src/BeholderPi
        remote: beholder
      notify: Restart discovery service

  handlers:
    - name: Restart discovery service
      systemd:
        name: beholder_discovery_sender
        state: restarted
        no_block: yes
      changed_when: False

- hosts: eyes
  remote_user: pi
  become: true

  tasks:
    - name: Populate service facts
      service_facts:

    - name: Update all installed apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
      ignore_errors: true
      no_log: true

    - name: Git setup | Update from 'spectator' remote to check
      become_user: pi
      git:
        repo: ssh://spectator/home/pi/src/BeholderPi
        update: yes
        dest: /home/pi/src/BeholderPi
        remote: spectator
      register: service_restart
      notify: Restart discovery service

    - name: Reload Systemd config
      systemd:
        daemon-reload: yes
      when: service_restart

    - name: Restart streaming service
      systemd:
        name: beholder_streaming
        state: restarted
      when: service_restart

  handlers:
    - name: Restart discovery service
      systemd:
        name: beholder_discovery_sender
        state: restarted
        no_block: yes
      changed_when: False
